image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: 'source'
  PROJECT_NAME: 'Huragok'
  BLAM_VARIANT:
    value: "HR"

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - .nuget/packages
    - '**/obj/project.assets.json'
    - '**/obj/*.csproj.nuget.*'

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'

stages:
  - build
  - test
  - release

build:
  stage: build
  parallel:
    matrix:
      - BLAM_VARIANT: ["HR"]
  script:
    - VERSION=$(dotnet msbuild Huragok.csproj -getProperty:VersionPrefix)
    - 'dotnet publish -c Release -r win-x64 -o publish-$BLAM_VARIANT -p:BlamVariant=$BLAM_VARIANT --no-restore --no-self-contained Huragok.csproj'
    - apt-get update && apt-get install -y zip
    - zip -r Huragok-$VERSION-$BLAM_VARIANT.zip publish-$BLAM_VARIANT/

  artifacts:
    paths:
      - Huragok-*.zip

tests:
  stage: test
  parallel:
    matrix:
      - BLAM_VARIANT: ["HR"]
  script:
    - 'dotnet test -c Release -p:BlamVariant=$BLAM_VARIANT --no-restore Huragok.csproj'

release:
  stage: release
  when: manual
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - VERSION=$(dotnet msbuild Huragok.csproj -getProperty:VersionPrefix)
    - ls

  release:
    tag_name: "v$VERSION"
    name: "Huragok v$VERSION"
    assets:
      links:
        - name: "HR Build"
          url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/Huragok-$VERSION-HR.zip"
    
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  
